config/routes.rb
Rails.application.routes.draw do
   get 'welcome/index'
   get 'events/index'
    mount ActionCable.server => '/cable'

  resources :groups
  resources :items
  resources :joineds
  resources :inviteds
  resources :friendships
  resources :orders
  resources :friendships_groups
  resources :password_resets

  get 'home/index'
  get 'latestorders/', to:'orders#latestorders'
 devise_for :users , :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  post '/set_friends' => 'orders#setfriends'
  get '/orders/orderDetails/:id' => 'orders#orderDetails'
  get '/InvitedFriends' => 'orders#InvitedFriends'
  get '/JoinedFriends' => 'orders#JoinedFriends'
  post '/orderDetails' => 'orders#AddorderDetails'
  post '/addfriends' =>'friendships#addFriend'
  post '/unfriend' =>'friendships#unfriend'
  post '/orders/finish' => 'orders#finish'
  post '/orders/load' => 'orders#load'
  post '/orders/invite' => 'orders#invite'
  post '/orders/get_data' => 'orders#get_data'
  post '/joineds/add' => 'joineds#add'
  post '/joineds/cancel' => 'joineds#cancel'


  authenticated :user do
   root 'home#index', as: 'authenticated_root'
  end
 # devise_scope :user do
 #   root 'devise/sessions#new'
 #  end
  resources :users
  root to: "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  after_create_commit{notify}
  belongs_to :invited
  private
  def notify
  	@uid = Invited.find(self.invited_id).user_id
  	@oid = Order.find(Invited.find(self.invited_id).order_id).id
  	@pic = User.find(Order.find(@oid).user_id).uimage (:thumb)
  	ActionCable.server.broadcast 'user_channel'+@uid.to_s, data: {msg: self.message, order_id: @oid, img: @pic, msgType: 1}
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
	belongs_to :user
	belongs_to :friend, :class_name => "User"
	has_and_belongs_to_many :groups
end

app/models/friendships_group.rb
class FriendshipsGroup < ApplicationRecord
	self.primary_keys = :Friendship_id, :group_id
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :friendships
end

app/models/invited.rb
class Invited < ApplicationRecord
  after_create_commit{create_event}
  belongs_to :order
  belongs_to :user
  has_many :events, :dependent => :destroy

 private
 def create_event
 	@name = User.find(Order.find(self.order_id).user_id).name
 	if Order.find(self.order_id).orderType
 		@orderType = "lunch"
 	else
 		@orderType = "breakfast"
 	end
 	@place = Order.find(self.order_id).place
 	@txt = @name+" invited you to "+@orderType+" from "+@place
 	@event = Event.create(message: @txt, invited_id: self.id, status: 0)
 end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :joined
end

app/models/joined.rb
class Joined < ApplicationRecord
  belongs_to :order
  belongs_to :user
  has_many :items
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :inviteds, dependent: :delete_all
  has_many :joineds, dependent: :delete_all
  
  has_attached_file :Menu, styles: { larg:"600x600>", medium: "300x300>", thumb: "50x50#" }
  validates_attachment_content_type :Menu, content_type: /\Aimage\/.*\z/

end

app/models/user.rb
class User < ApplicationRecord

  has_attached_file :uimage, styles: { larg:"600x600>", medium: "300x300>", thumb: "50x50#" }
  validates_attachment_content_type :uimage, content_type: /\Aimage\/.*\z/

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable ,:omniauthable, :omniauth_providers => [:google_oauth2, :facebook]

  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :orders
  has_many :inviteds
  has_many :joineds
  has_many :groups


  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
         user.password = Devise.friendly_token[0,20]
        user.name = auth.info.name   # assuming the user model has a name
        # user.image = auth.info.image # assuming the user model has an image
      end
    end
  
def send_password_reset
  generate_token(:password_reset_token)
  self.password_reset_sent_at = Time.zone.now
  save!
  UserMailer.password_reset(self).deliver
  
end

  def generate_token(column)

    begin
  
      self[column] = SecureRandom.urlsafe_base64  
    end while user.exists?(column => self[column])
  
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index

  	if current_user
		@orders = Order.all.where(user_id: current_user.id).order(created_at: :desc) 
		# --------------------------
		@all = []
		current_user.friends.each { |friends|
			@all.push friends.orders
		}
		puts "Al"
		puts @all.inspect
		# @all = Order.joins(:user).select("*")

	else
    	redirect_to '/users/sign_in'
    end
  end
end

app/controllers/inviteds_controller.rb
class InvitedsController < ApplicationController
  before_action :set_invited, only: [:show, :edit, :update, :destroy]

  # GET /inviteds
  # GET /inviteds.json
  def index
    @inviteds = Invited.all
  end

  # GET /inviteds/1
  # GET /inviteds/1.json
  def show
  end

  # GET /inviteds/new
  def new
    @invited = Invited.new
  end

  # GET /inviteds/1/edit
  def edit
  end

  # POST /inviteds
  # POST /inviteds.json
  def create
    @invited = Invited.new(invited_params)

    respond_to do |format|
      if @invited.save
        format.html { redirect_to @invited, notice: 'Invited was successfully created.' }
        format.json { render :show, status: :created, location: @invited }
      else
        format.html { render :new }
        format.json { render json: @invited.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inviteds/1
  # PATCH/PUT /inviteds/1.json
  def update
    respond_to do |format|
      if @invited.update(invited_params)
        format.html { redirect_to @invited, notice: 'Invited was successfully updated.' }
        format.json { render :show, status: :ok, location: @invited }
      else
        format.html { render :edit }
        format.json { render json: @invited.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inviteds/1
  # DELETE /inviteds/1.json
  def destroy
    @events = Event.where(invited_id: @invited.id)
    @events.each do |e|
      e.destroy
    end
    @invited.destroy
    respond_to do |format|
      format.html { redirect_to inviteds_url, notice: 'Invited was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invited
      @invited = Invited.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invited_params
      params.require(:invited).permit(:order_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inviteds_helper.rb
module InvitedsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/joineds_helper.rb
module JoinedsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/inviteds/_form.html.erb
<%= form_with(model: invited, local: true) do |form| %>
  <% if invited.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invited.errors.count, "error") %> prohibited this invited from being saved:</h2>

      <ul>
      <% invited.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :order_id %>
    <%= form.text_field :order_id, id: :invited_order_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :invited_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/inviteds/edit.html.erb
<h1>Editing Invited</h1>

<%= render 'form', invited: @invited %>

<%= link_to 'Show', @invited %> |
<%= link_to 'Back', inviteds_path %>

app/views/inviteds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inviteds</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inviteds.each do |invited| %>
      <tr>
        <td><%= invited.order %></td>
        <td><%= invited.user %></td>
        <td><%= link_to 'Show', invited %></td>
        <td><%= link_to 'Edit', edit_invited_path(invited) %></td>
        <td><%= link_to 'Destroy', invited, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invited', new_invited_path %>

app/views/inviteds/new.html.erb
<h1>New Invited</h1>

<%= render 'form', invited: @invited %>

<%= link_to 'Back', inviteds_path %>

app/views/inviteds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @invited.order %>
</p>

<p>
  <strong>User:</strong>
  <%= @invited.user %>
</p>

<%= link_to 'Edit', edit_invited_path(@invited) %> |
<%= link_to 'Back', inviteds_path %>