config/routes.rb
Rails.application.routes.draw do
   get 'welcome/index'
   get 'events/index'
    mount ActionCable.server => '/cable'

  resources :groups
  resources :items
  resources :joineds
  resources :inviteds
  resources :friendships
  resources :orders
  resources :friendships_groups
  resources :password_resets

  get 'home/index'
  get 'latestorders/', to:'orders#latestorders'
 devise_for :users , :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  post '/set_friends' => 'orders#setfriends'
  get '/orders/orderDetails/:id' => 'orders#orderDetails'
  get '/InvitedFriends' => 'orders#InvitedFriends'
  get '/JoinedFriends' => 'orders#JoinedFriends'
  post '/orderDetails' => 'orders#AddorderDetails'
  post '/addfriends' =>'friendships#addFriend'
  post '/unfriend' =>'friendships#unfriend'
  post '/orders/finish' => 'orders#finish'
  post '/orders/load' => 'orders#load'
  post '/orders/invite' => 'orders#invite'
  post '/orders/get_data' => 'orders#get_data'
  post '/joineds/add' => 'joineds#add'
  post '/joineds/cancel' => 'joineds#cancel'


  authenticated :user do
   root 'home#index', as: 'authenticated_root'
  end
 # devise_scope :user do
 #   root 'devise/sessions#new'
 #  end
  resources :users
  root to: "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  after_create_commit{notify}
  belongs_to :invited
  private
  def notify
  	@uid = Invited.find(self.invited_id).user_id
  	@oid = Order.find(Invited.find(self.invited_id).order_id).id
  	@pic = User.find(Order.find(@oid).user_id).uimage (:thumb)
  	ActionCable.server.broadcast 'user_channel'+@uid.to_s, data: {msg: self.message, order_id: @oid, img: @pic, msgType: 1}
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
	belongs_to :user
	belongs_to :friend, :class_name => "User"
	has_and_belongs_to_many :groups
end

app/models/friendships_group.rb
class FriendshipsGroup < ApplicationRecord
	self.primary_keys = :Friendship_id, :group_id
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :friendships
end

app/models/invited.rb
class Invited < ApplicationRecord
  after_create_commit{create_event}
  belongs_to :order
  belongs_to :user
  has_many :events, :dependent => :destroy

 private
 def create_event
 	@name = User.find(Order.find(self.order_id).user_id).name
 	if Order.find(self.order_id).orderType
 		@orderType = "lunch"
 	else
 		@orderType = "breakfast"
 	end
 	@place = Order.find(self.order_id).place
 	@txt = @name+" invited you to "+@orderType+" from "+@place
 	@event = Event.create(message: @txt, invited_id: self.id, status: 0)
 end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :joined
end

app/models/joined.rb
class Joined < ApplicationRecord
  belongs_to :order
  belongs_to :user
  has_many :items
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :inviteds, dependent: :delete_all
  has_many :joineds, dependent: :delete_all
  
  has_attached_file :Menu, styles: { larg:"600x600>", medium: "300x300>", thumb: "50x50#" }
  validates_attachment_content_type :Menu, content_type: /\Aimage\/.*\z/

end

app/models/user.rb
class User < ApplicationRecord

  has_attached_file :uimage, styles: { larg:"600x600>", medium: "300x300>", thumb: "50x50#" }
  validates_attachment_content_type :uimage, content_type: /\Aimage\/.*\z/

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable ,:omniauthable, :omniauth_providers => [:google_oauth2, :facebook]

  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :orders
  has_many :inviteds
  has_many :joineds
  has_many :groups


  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
         user.password = Devise.friendly_token[0,20]
        user.name = auth.info.name   # assuming the user model has a name
        # user.image = auth.info.image # assuming the user model has an image
      end
    end
  
def send_password_reset
  generate_token(:password_reset_token)
  self.password_reset_sent_at = Time.zone.now
  save!
  UserMailer.password_reset(self).deliver
  
end

  def generate_token(column)

    begin
  
      self[column] = SecureRandom.urlsafe_base64  
    end while user.exists?(column => self[column])
  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inviteds_helper.rb
module InvitedsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/joineds_helper.rb
module JoinedsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Otlob</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'animate', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'style', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'bootstrap', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'style', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application'%>
  </head>

  <body>
  <div class="gtco-loader"></div>

  <nav class="gtco-nav" role="navigation">

    <div class="gtco-container">

      <div class="row">
        <div class="col-sm-4 col-xs-4">
          <div id="gtco-logo">
            <%= image_tag("otlop.png", class: "img-responsive image", id: "navbar-logo") %>
          </div>
        </div>
              <div class="col-xs-8 text-right menu-1">
          <ul>

             <% if user_signed_in? %>
                <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
              <% else %>
                <li><%= link_to('Login', new_user_session_path)  %>  </li>

              <% end %>

              <!-- Notification Icon -->
                <li class="nav-item dropdown">
                  <a class="nav-link text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-bell"></i>
                  </a>
                    <ul class="dropdown-menu">
                      <li class="head text-light bg-dark">
                        <div class="row">
                          <div class="col-lg-12 col-sm-12 col-12"  style="color: black">
                            <span style="float: left; margin-left: 30px; color: blue">Notifications</span>
                          </div>
                      </li>
                      <ul id="notify">
                      <!-- <div id="notify"></div> -->
                      <% if @notifications.size !=0 %>
                      <% @notifications.reverse.each do |n| %>

                      <li class="notification-box">
                        <div class="row">
                          <div class="col-lg-6 col-sm-6 col-6 text-center">
                            <img src="<%= User.find(Order.find(Invited.find(n.invited_id).order_id).user_id).uimage (:thumb) %>" class="w-50" style="float: left; margin-left: 10px;">
                          </div>
                          <div class="col-lg-12 col-sm-12 col-12" style="color: black; margin-left: 10px;"><%= n.message %> <%= time_ago_in_words(n.created_at) %> ago</div>
                          <%= n.status %>
                          <% if n.status==0 %>
                          <button id="<%= Invited.find(n.invited_id).order_id %>" style="background-color: #4CAF50; color: white" onclick="joinOrder(this)">Join</button>
                          <button style="background-color: #f44336; color: white" onclick="cancelOrder(this)">Cancel</button>
                          <% elsif n.status==1 %>
                          <button id="<%= Invited.find(n.invited_id).order_id %>" style="background-color: #4CAF50; color: white" onclick="goOrder(this)">Go</button>
                          <% end %>
                        </div>
                        <div role="separator" class="divider"></div>
                      </li>
                      <% end %>
                      <% end %>
                      </ul>
                      <li class="bg-dark text-center">
                        <a href="/events/index" class="text-light" style="color: blue">View All</a>
                      </li>
                    </ul>
                </li>
            <!-- end notificatuion -->
            <li class="nav-item active">
              <%= link_to 'Home |' , home_index_url , :class => "btn-cta" %>
            </li>
            <li class="nav-item">

              <%= link_to 'Friends |' , new_friendship_url , :class => "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Groups |' , groups_url , :class => "btn-cta" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Orders |' , orders_url , :class => "btn-cta" %>
            </li>
          </ul>
        </div>
      </div>
      </div>
    </nav>

    <div class="footer">
      <p>Copy Rights resreved for Otlob©</p>

    </div>

    <%= yield %>
    <%= javascript_include_tag 'notify'%>
    <%= javascript_include_tag 'JSGroups'%>
    <%= javascript_include_tag 'jquery.min'%>
    <%= javascript_include_tag 'jquery.waypoints.min'%>
    <%= javascript_include_tag 'main'%>
    <%= javascript_include_tag 'owl.carousel.min'%>
    <%= javascript_include_tag 'orderJs'%>


  </body>
</html>

app/views/layouts/latestorders.html.erb
<!DOCTYPE html>
<html lang="en" >
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body style="background-color:pink;">

<div class="container">


  <button type="button" class="btn btn-primary">Home</button>
  <button type="button" class="btn btn-success">Friends</button>
  <button type="button" class="btn btn-info">Groups</button>
  
  <button type="button" class="btn btn-danger">orders</button>
  
   <ul class="nav navbar-nav navbar-right">
  
  <a href="#">
          <span class="glyphicon glyphicon-bell"></span>
        </a>

  
  <span CLASS  
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-user"></span>&nbsp;
                        <strong>REEM</strong>
                        <span class="glyphicon glyphicon-chevron-down"></span>
                        
                   </a>
               </li>
 </span>
                        
        <a href="#">
          <span class="glyphicon glyphicon-log-out"></span>
        </a>
                    </a>
                    <!--<a href="#" class="btn btn-info btn-lg">-->
          <!--<span class="glyphicon glyphicon-log-out">Log out</span> -->
        </a>
             </ul>   
             <ul></ul>
             <ul></ul>
             <ul>.</ul>
             <div></div>
             
   <div class="row main col-lg-9 myHalfCol ">
   		<div class="col-lg-6">
			<h2>latest orders</h2>
            <div class "align:center" ="list-group">
    			<a href="#" class="list-group-item list-group-item-success">lunch</a>
    			<a href="#" class="list-group-item list-group-item-info">Second item</a>
    			<a href="#" class="list-group-item list-group-item-warning">Third item</a>
    			<a href="#" class="list-group-item list-group-item-danger">Fourth item</a>
  			</div> 
        </div>
  
   		<div class="col-lg-6">
   			<h2>Friends list</h2>
              	<div class="row list-group">
    				<a href="#" class="list-group-item list-group-item-success">REEM</a>
                    <a href="#" class="list-group-item list-group-item-info">Mary</a>
                    <a href="#" class="list-group-item list-group-item-warning">Mahmoud</a>
                    <a href="#" class="list-group-item list-group-item-danger">Eslam</a>
  				</div> 
   		</div>
   </div>

</body>
</html>